using MyNamespace; // only generated by MSBuild Task

namespace MSBuild.Test
{
    public class TestClass
    {
        public TestClass() 
        {
            // All classes below are generated by the MSBuild Task
            var c1 = new Class1();
            var c2 = new Class2();
            var c3 = new Class3();
            var mf = new MyFirstClass();
            var ms = new MySecondClass();
        }

    }
}
