//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Dapper;
using System.ComponentModel;

namespace CodegenCS.AdventureWorksPOCOSample
{
    [Table("ShoppingCartItem", Schema = "Sales")]
    public partial class ShoppingCartItem : INotifyPropertyChanged
    {
        #region Members
        private int _shoppingCartItemId;
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ShoppingCartItemId 
        { 
            get { return _shoppingCartItemId; } 
            set { SetField(ref _shoppingCartItemId, value, nameof(ShoppingCartItemId)); } 
        }
        private DateTime _dateCreated;
        public DateTime DateCreated 
        { 
            get { return _dateCreated; } 
            set { SetField(ref _dateCreated, value, nameof(DateCreated)); } 
        }
        private DateTime _modifiedDate;
        public DateTime ModifiedDate 
        { 
            get { return _modifiedDate; } 
            set { SetField(ref _modifiedDate, value, nameof(ModifiedDate)); } 
        }
        private int _productId;
        public int ProductId 
        { 
            get { return _productId; } 
            set { SetField(ref _productId, value, nameof(ProductId)); } 
        }
        private int _quantity;
        public int Quantity 
        { 
            get { return _quantity; } 
            set { SetField(ref _quantity, value, nameof(Quantity)); } 
        }
        private string _shoppingCartId;
        public string ShoppingCartId 
        { 
            get { return _shoppingCartId; } 
            set { SetField(ref _shoppingCartId, value, nameof(ShoppingCartId)); } 
        }
        #endregion Members

        #region ActiveRecord
        public void Save()
        {
            if (ShoppingCartItemId == default(int))
                Insert();
            else
                Update();
        }
        public void Insert()
        {
            using (var conn = IDbConnectionFactory.CreateConnection())
            {
                string cmd = @"
                INSERT INTO [Sales].[ShoppingCartItem]
                (
                    [DateCreated],
                    [ModifiedDate],
                    [ProductID],
                    [Quantity],
                    [ShoppingCartID]
                )
                VALUES
                (
                    @DateCreated,
                    @ModifiedDate,
                    @ProductId,
                    @Quantity,
                    @ShoppingCartId
                )";

                this.ShoppingCartItemId = conn.Query<int>(cmd + "SELECT SCOPE_IDENTITY();", this).Single();
            }
        }
        public void Update()
        {
            using (var conn = IDbConnectionFactory.CreateConnection())
            {
                string cmd = @"
                UPDATE [Sales].[ShoppingCartItem] SET
                    [DateCreated] = @DateCreated,
                    [ModifiedDate] = @ModifiedDate,
                    [ProductID] = @ProductId,
                    [Quantity] = @Quantity,
                    [ShoppingCartID] = @ShoppingCartId
                WHERE
                    [ShoppingCartItemID] = @ShoppingCartItemId";
                conn.Execute(cmd, this);
            }
        }
        #endregion ActiveRecord

        #region Equals/GetHashCode
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }
            if (ReferenceEquals(this, obj))
            {
                return true;
            }
            ShoppingCartItem other = obj as ShoppingCartItem;
            if (other == null) return false;

            if (DateCreated != other.DateCreated)
                return false;
            if (ModifiedDate != other.ModifiedDate)
                return false;
            if (ProductId != other.ProductId)
                return false;
            if (Quantity != other.Quantity)
                return false;
            if (ShoppingCartId != other.ShoppingCartId)
                return false;
            return true;
        }
        public override int GetHashCode()
        {
            unchecked
            {
                int hash = 17;
                hash = hash * 23 + (DateCreated == default(DateTime) ? 0 : DateCreated.GetHashCode());
                hash = hash * 23 + (ModifiedDate == default(DateTime) ? 0 : ModifiedDate.GetHashCode());
                hash = hash * 23 + (ProductId == default(int) ? 0 : ProductId.GetHashCode());
                hash = hash * 23 + (Quantity == default(int) ? 0 : Quantity.GetHashCode());
                hash = hash * 23 + (ShoppingCartId == null ? 0 : ShoppingCartId.GetHashCode());
                return hash;
            }
        }
        public static bool operator ==(ShoppingCartItem left, ShoppingCartItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ShoppingCartItem left, ShoppingCartItem right)
        {
            return !Equals(left, right);
        }

        #endregion Equals/GetHashCode

        #region INotifyPropertyChanged/IsDirty
        public HashSet<string> ChangedProperties = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        public void MarkAsClean()
        {
            ChangedProperties.Clear();
        }
        public virtual bool IsDirty => ChangedProperties.Any();

        public event PropertyChangedEventHandler PropertyChanged;
        protected void SetField<T>(ref T field, T value, string propertyName) {
            if (!EqualityComparer<T>.Default.Equals(field, value)) {
                field = value;
                ChangedProperties.Add(propertyName);
                OnPropertyChanged(propertyName);
            }
        }
        protected virtual void OnPropertyChanged(string propertyName) {
            if (PropertyChanged != null) {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
        #endregion INotifyPropertyChanged/IsDirty
    }
}
